omage: python3.3
script:
    - pip install -U .

notification:
    slack:
        on_started: true
        on_success: true
        on_failure: true
        team: connectical
        channel: '#git'
        username: builder
        token: {{slackToken}}
